import { chatWin-input } from "chatWin-input.slint";
import { styles } from "../styles.slint";
export component chatWindow {
    VerticalLayout {
        spacing: styles.margin;
        Rectangle {
            border-radius: styles.border-radius;
            background: styles.theme.container.background;
            vertical-stretch: 1;
            Text {
                color: styles.theme.container.text;
                text: "chat window";
            }
        }

        chatWin-input {
            
            height: 50px;
        }
    }
}
