import { chatWin-input } from "inputBar.slint";
import { styles } from "../styles.slint";
export component chatWindow {
    VerticalLayout {
        spacing: styles.margin;
        Rectangle {
            border-radius: styles.border-radius;
            background: styles.theme.container.background;
            vertical-stretch: 1;
            Text {
                color: styles.theme.container.text;
                text: "Content Area";
            }
        }

        chatWin-input {
            // min-height: 52px;
        }
    }
}
