import { styles } from "../styles.slint";
import { TextEdit, VerticalBox } from "std-widgets.slint";
export component chatWin-input {
    Rectangle {
        background: styles.theme.container.background;
        border-radius: styles.border-radius;
        VerticalBox {
            padding: 16px;
            TextInput {
                enabled: true;
                color: self.has-focus ? styles.theme.container.text : styles.theme.container.ghost-text;
                font-size: 16px;
                horizontal-alignment: TextHorizontalAlignment.left;
                text: self.has-focus ? "" : "Typing in...";
                wrap: TextWrap.word-wrap;
                font-family: "Lexend";
                single-line: false;
            }
        }
    }
}
