import { styles } from "../styles.slint";
import { TextEdit, VerticalBox } from "std-widgets.slint";
export component chatWin-input inherits Rectangle {
    in-out property <string> text <=> input.text;

    background: styles.theme.container.background;
    border-radius: 6px;
    VerticalBox {
        padding: 16px;

        input := TextInput {
            color: styles.theme.container.text;
            font-size: 16px;
            horizontal-alignment: TextHorizontalAlignment.left;
            wrap: TextWrap.word-wrap;
            font-family: "Lexend";
            single-line: true;

            accepted => {
                text = "";
            }
        }
    }

    Text {
        text: "Typing in...";
        color: styles.theme.container.ghost-text;
        x: input.x;
        y: input.y;
        font-size: 16px;

        visible: input.text == "";
    }
}
