import { styles } from "../styles.slint";
import { TextEdit, VerticalBox } from "std-widgets.slint";
export component chatWin-input {
    Rectangle {
        background: styles.theme.container.background;
        border-radius: styles.border-radius;
        VerticalBox {
            padding: 16px;
            TextInput {
                enabled: true;
                color: styles.theme.container.text;
                font-size: 16px;
                horizontal-alignment: TextHorizontalAlignment.left;
                text: "Placeholder Text";
                wrap: TextWrap.word-wrap;
                font-family: "Lexend";
                single-line: false;
            }
        }
    }
}