import { styles } from "../styles.slint";

export component serverList {
    Rectangle {
        x: 0;
        background: styles.theme.container.background;
        border-radius: styles.border-radius;
        VerticalLayout {
            spacing: styles.margin;
            Text {
                color: styles.theme.container.text;
                text: "Server List";
            }
        }
    }
}
