import { styles } from "../styles.slint";
import { serverList } from "serverList.slint";
import { channelList } from "channelList.slint";

export component sidebar {
    Rectangle {
        HorizontalLayout {
            spacing: styles.margin;
            serverList {
                width: 66px;
            }
            channelList {
                horizontal-stretch: 1;
            }
        }
        background: styles.theme.background;
    }
}
