import { styles } from "../styles.slint";

export component userPanel {
    TouchArea {
        height: self.has-hover ? 60px : 25px;
        y: parent.height - self.height;
        animate height {
            duration: 200ms;
            easing: styles.easing;
        }
        mouse-cursor: pointer;
        Rectangle {
            background: styles.theme.accent.background;
            border-top-left-radius: styles.border-radius * 2;
            border-top-right-radius: styles.border-radius * 2;
            HorizontalLayout {
            }
        }
    }
}