import { sidebar } from "../components/sidebar.slint";
import { styles } from "../styles.slint";
import { chatWindow } from "../components/contentPanel.slint";

export component mainView {
    in-out property <length> dividerPosition: 250px;
    property <bool> dragging: false;
    
    HorizontalLayout {
        padding: styles.margin;
        spacing: styles.margin / 2;
        
        sidebar-container := Rectangle {
            width: dividerPosition;
            
            sidebar {
                width: parent.width;
                height: parent.height;
            }
        }
        
        divider := Rectangle {
            width: 0px;
            // background: dragging ? @linear-gradient(180deg, transparent 0%, styles.theme.accent.container 50%, transparent 100%) : styles.theme.background;
            background: dragging ? styles.theme.container.floating : styles.theme.background;
            border-radius: 3px;
            animate background {
                duration: 100ms;
                easing: ease-out;
            }
            
            TouchArea {
                width: 11px;
                x: -4px;
                mouse-cursor: ew-resize;
                
                moved => {
                    if (self.pressed) {
                        dividerPosition = max(150px, min(root.width - 150px - self.width, dividerPosition + self.mouse-x - self.pressed-x));
                    }
                }
                
                pointer-event(event) => {
                    if (event.kind == PointerEventKind.down) {
                        dragging = true;
                    } else if (event.kind == PointerEventKind.up || event.kind == PointerEventKind.cancel) {
                        dragging = false;
                    }
                }
            }
        }
        
        chatWindow {}
    }
}
